from bert.BertProcessor import BertProcessor
from evaluator.StoryQualityEvaluator import StoryQualityEvaluator
from utills.VectorUtill import VectorUtill
from scipy.spatial.distance import cosine

## bertProcessor = BertProcessor()
storyQualityEvaluator = StoryQualityEvaluator()

vector = VectorUtill()

p = "Sam and Judy went out for dinner at their favorite restaurant. While driving to the restaurant, Judy’s favorite song played on the radio. Sam found a parking space at the very front of the restaurant. Sam and Judy were seated immediately and ordered their favorite food to the waiter. He looked distracted and tired but was polite while taking their order. Sam’s favorite song played on the radio while they waited for their food. When the waiter returned with their food it was all wrong! The waiter apologized and returned a few minutes later with the correct order. Sam and Judy enjoyed their meal. They paid their tab, left a tip for the waiter, and drove back home."
p2 = "Twenty-two, I was with my first lover, not college-girl exploring but the real deal. She was 28 and had an even older long-distance partner who was visiting, so we went out for coffee drinks. Playing just friends. I’d never had one before; it was divine, sweet Bailey’s flame searing night mocha, whipped cream-topped glass mug, shaved chocolate. Her partner paid, magnanimous, husky and tanned, clueless or so it seemed. I was smug, silky, sitting back watching my lover managing. Later, when she cheated on me too, I called her partner, trying to commiserate. And that was some hot wet salt."
p3 = "Curiosity and intrigue lifelong companions. Shell question everything, even the origin of trees. She fears them at night when the wind races through like a freight train mimicking the clamoring and wailing of voices."
p4 = "She arrived with clenched fists, wide eyes, and strong lungs. During the cleaning, the elders caught her stretching her neck, peering into the darkness of a near past. This would be her lot in life: a bellowing voice, roaming eyes, and a sankofa spirit. Curiosity and intrigue lifelong companions. She’ll question everything, even the origin of trees. She fears them at night when the wind races through like a freight train mimicking the clamoring and wailing of voices. She’ll demand to know who’s there and consider each tap, scratch, and drag a clue, a direct path to the other side."
text = "After stealing money from the bank vault, the bank robber was seen " \
       "fishing on the Mississippi river bank."

p5 = "Confusion and chaos lifted. All was still and clear in his mind. Only hours earlier he was filled with misery, self-loathing and desperation. But now the lycanthropic curse had taken control, freed from its chains and eager to make up for lost time. Jagged claws easily removed the clothes from his body. He would have no more use for them. He had emerged beside a small, shallow river which was painted silver under the clear sky. It was cold, the dead of winter, and his breath misted before his eyes. The weather did not bother him. This body was made for endurance. His long, wiry limbs held easy strength. He felt a buzzing run through his whole body. An electrically charged energy that needed to be unleashed. His magnified senses announced the presence of all living creatures within running distance. None could defy him, none could oppose him. All would flee before him. But it would make no difference. This night would be coloured in blood. He threw back his head and let out a howl of hysteria, elation and fervour. The night belonged to him. The full moon was risen and the chase was on."
p6 = "In eighth grade, I wore tons of make-up to Catholic school. I was a rebel. Trying to hide my outbreaks, I covered them with a layer of Clearasil beneath my beige foundation and powder. But it wasn’t just about my bad complexion. Oh no. I wanted to look like a movie star, like Elizabeth Taylor or Sophia Loren. I penciled in my eyebrows with black eyebrow pencil, jet-black eyeliner thickly lining my eyes, and I topped it all off with jade green eye-shadow that came in a long tube something like a lipstick. My mouth I left blank. This made my eyes stand out more. The fact that we weren’t allowed to wear make-up to school created all this excitement in me, and one day when Sister Theonilla was walking down the aisle in her long black robe, her wire-rim glasses perched on her nose and her skin the color of oatmeal, she stopped at my desk, moved in closer and slowly ran her index finger across my eyelid. The tip of her finger came back green. “I’m not wearing make-up,” I said defiantly. Oh, the thrill of it. This was the beginning of my long career as a liar."
p7 = "It was only 2:00 in the morning. Finding that she could not go back to sleep, she slowly got out of bed and walked downstairs to the kitchen. Putting on an apron, she created the filling by mixing ground pork, chives, minced garlic and soy sauce- amongst other ingredients- together. Then, taking the freshly-kneaded dough, she rolled it into several thin sheets. When the ingredients were prepared, she placed a thin sheet of dough on the palm of her hand and gently scooped up some of the filling-placing it at the center of the dough sheet and pinching the ends of the dough sheet together. That process she repeated until there was no more filling and sheets of dough left. Afterwards, she stir-fried the individually-wrapped fillings in oil until they got crispy. Placing the Chinese dumplings on a plate, she took out a pair of chopsticks and began savoring the taste. When she had a hard time sleeping at night, eating her dumplings would always help. She didn’t really know why, but perhaps it is because they reminded her of her roots; through them, she remembered the old home she used to live in with her family back in China."

## keep this story
p8 = "As the young couple strolled hand in hand through the park, a gust of wind whipped through the trees, sending a chill down their spines. It was as if the very air around them was trying to warn them of something sinister lurking just out of sight. But they shrugged off the feeling, dismissing it as nothing more than their overactive imaginations. They were in love, after all, and nothing could dampen their spirits. As they continued on their way, the clouds overhead grew darker and more ominous. A few drops of rain began to fall, followed by a rumble of thunder that echoed through the park. Still, the couple remained undaunted. They laughed and danced in the rain, oblivious to the danger that lurked just around the corner. But then, out of nowhere, a bolt of lightning struck a nearby tree, sending splinters flying in every direction. The couple shrieked and stumbled backwards, their hearts racing with fear. As they looked up at the sky, they realized that they had been foolish to ignore the warning signs. The clouds had been a deep shade of gray, the wind had been howling, and the air had been charged with electricity. All of the lesser words of foreshadowing had been there, but they had ignored them, too caught up in their own happiness to pay attention. As they huddled together, waiting for the storm to pass, they knew that they had been lucky. They had narrowly escaped disaster, but they had learned an important lesson. From now on, they would pay closer attention to the world around them, for they knew that the smallest details could hold the greatest warnings."

## keep this story
p9 = "Lena was a young girl who lived in a small village at the edge of a dense forest. She loved to explore the woods and often spent her afternoons wandering among the trees. One day, while she was out on a walk, she noticed a strange feeling in the air. It was as if the forest was holding its breath, waiting for something to happen. As Lena walked deeper into the woods, she began to see signs of danger. Trees were toppled over, and the underbrush was trampled down. The forest animals were nowhere to be seen, and the silence was eerie. Lena could feel her heart racing as she realized that something terrible had happened. As she continued on her path, Lena saw a shadow moving in the distance. It was too dark to make out what it was, but she knew that it wasn't human. She tried to turn back, but it was too late. The shadow was upon her, and Lena found herself face to face with a fearsome creature she had never seen before. Lena fought for her life, but the creature was too strong. She managed to escape, but she knew that she would never be the same again. From that day on, Lena never ventured into the forest alone, and the villagers whispered of the dangers that lurked in the woods. Years later, when Lena was an old woman, the village was attacked by a pack of savage beasts. Lena knew that they were the same creatures that had attacked her all those years ago. She fought bravely alongside the other villagers, but in the end, they were all killed. As Lena lay dying, she realized that the foreshadowing she had felt all those years ago had been a warning of the terrible fate that awaited her village."


## keep this story (chatGPT worked)
p10 = "Sophie was an avid reader who loved to explore the world of books. One day, while browsing through the shelves of her local library, she stumbled upon a mysterious old tome. The cover was worn and tattered, and the pages were yellowed with age. As she opened the book, Sophie felt a strange sensation wash over her. It was as if she had been transported to another time and place. The story within the pages was unlike anything she had ever read before, filled with twists and turns that kept her on the edge of her seat. As she read on, Sophie couldn't help but feel a sense of wonder and excitement. The words seemed to jump off the page, painting vivid pictures in her mind. The characters were so real, she felt as if she knew them personally. Before she knew it, hours had passed, and the library was closing for the night. As she closed the book, Sophie felt a pang of sadness, as if she was saying goodbye to dear friends. Over the coming days, Sophie found herself unable to stop thinking about the story. She re-read it several times, each time uncovering new details and hidden meanings. In the end, Sophie realized that the story had become more than just words on a page. It was a world she could escape to whenever she needed to, a place of wonder and magic that would always be there for her. And she knew that no matter how many books she read in the future, this one would always hold a special place in her heart."

p11 = "Once upon a time, there was a young boy named Peter who lived in a small village at the foot of a mountain. Peter loved to explore and play in the woods near his home, and he dreamed of one day climbing to the top of the mountain to see the world from above. One day, Peter decided to make his dream a reality. He packed some food, water, and warm clothes into a backpack and set out on his journey up the mountain. The climb was steep and difficult, but Peter was determined to reach the top. As he climbed higher and higher, Peter encountered all sorts of challenges, from rocky outcroppings to treacherous cliff faces. But he persevered, using his wits and his strength to overcome each obstacle in turn. Finally, after many hours of climbing, Peter reached the summit of the mountain. He gazed out at the breathtaking vista before him, feeling a sense of accomplishment and wonder unlike anything he had ever experienced before. As he made his way back down the mountain, Peter knew that his life would never be the same. He had discovered something within himself that he had never known existed - a determination and strength of character that he could draw upon for the rest of his days."

storyQualityEvaluator.initiateBertProcess(p11)
storyQualityEvaluator.computeMovingCosineSimilarity()
storyQualityEvaluator.plotCosineSimilaritiesBySentenceWord()