from evaluator.StoryQualityEvaluator import StoryQualityEvaluator
from utills.VectorUtill import VectorUtill

## bertProcessor = BertProcessor()
storyQualityEvaluator = StoryQualityEvaluator()

vector = VectorUtill()

p = "Sam and Judy went out for dinner at their favorite restaurant. While driving to the restaurant, Judy’s favorite song played on the radio. Sam found a parking space at the very front of the restaurant. Sam and Judy were seated immediately and ordered their favorite food to the waiter. He looked distracted and tired but was polite while taking their order. Sam’s favorite song played on the radio while they waited for their food. When the waiter returned with their food it was all wrong! The waiter apologized and returned a few minutes later with the correct order. Sam and Judy enjoyed their meal. They paid their tab, left a tip for the waiter, and drove back home."
p2 = "Twenty-two, I was with my first lover, not college-girl exploring but the real deal. She was 28 and had an even older long-distance partner who was visiting, so we went out for coffee drinks. Playing just friends. I’d never had one before; it was divine, sweet Bailey’s flame searing night mocha, whipped cream-topped glass mug, shaved chocolate. Her partner paid, magnanimous, husky and tanned, clueless or so it seemed. I was smug, silky, sitting back watching my lover managing. Later, when she cheated on me too, I called her partner, trying to commiserate. And that was some hot wet salt."
p3 = "Curiosity and intrigue lifelong companions. Shell question everything, even the origin of trees. She fears them at night when the wind races through like a freight train mimicking the clamoring and wailing of voices."
p4 = "She arrived with clenched fists, wide eyes, and strong lungs. During the cleaning, the elders caught her stretching her neck, peering into the darkness of a near past. This would be her lot in life: a bellowing voice, roaming eyes, and a sankofa spirit. Curiosity and intrigue lifelong companions. She’ll question everything, even the origin of trees. She fears them at night when the wind races through like a freight train mimicking the clamoring and wailing of voices. She’ll demand to know who’s there and consider each tap, scratch, and drag a clue, a direct path to the other side."
text = "After stealing money from the bank vault, the bank robber was seen " \
       "fishing on the Mississippi river bank."

p5 = "Confusion and chaos lifted. All was still and clear in his mind. Only hours earlier he was filled with misery, self-loathing and desperation. But now the lycanthropic curse had taken control, freed from its chains and eager to make up for lost time. Jagged claws easily removed the clothes from his body. He would have no more use for them. He had emerged beside a small, shallow river which was painted silver under the clear sky. It was cold, the dead of winter, and his breath misted before his eyes. The weather did not bother him. This body was made for endurance. His long, wiry limbs held easy strength. He felt a buzzing run through his whole body. An electrically charged energy that needed to be unleashed. His magnified senses announced the presence of all living creatures within running distance. None could defy him, none could oppose him. All would flee before him. But it would make no difference. This night would be coloured in blood. He threw back his head and let out a howl of hysteria, elation and fervour. The night belonged to him. The full moon was risen and the chase was on."
p6 = "In eighth grade, I wore tons of make-up to Catholic school. I was a rebel. Trying to hide my outbreaks, I covered them with a layer of Clearasil beneath my beige foundation and powder. But it wasn’t just about my bad complexion. Oh no. I wanted to look like a movie star, like Elizabeth Taylor or Sophia Loren. I penciled in my eyebrows with black eyebrow pencil, jet-black eyeliner thickly lining my eyes, and I topped it all off with jade green eye-shadow that came in a long tube something like a lipstick. My mouth I left blank. This made my eyes stand out more. The fact that we weren’t allowed to wear make-up to school created all this excitement in me, and one day when Sister Theonilla was walking down the aisle in her long black robe, her wire-rim glasses perched on her nose and her skin the color of oatmeal, she stopped at my desk, moved in closer and slowly ran her index finger across my eyelid. The tip of her finger came back green. “I’m not wearing make-up,” I said defiantly. Oh, the thrill of it. This was the beginning of my long career as a liar."
p7 = "It was only 2:00 in the morning. Finding that she could not go back to sleep, she slowly got out of bed and walked downstairs to the kitchen. Putting on an apron, she created the filling by mixing ground pork, chives, minced garlic and soy sauce- amongst other ingredients- together. Then, taking the freshly-kneaded dough, she rolled it into several thin sheets. When the ingredients were prepared, she placed a thin sheet of dough on the palm of her hand and gently scooped up some of the filling-placing it at the center of the dough sheet and pinching the ends of the dough sheet together. That process she repeated until there was no more filling and sheets of dough left. Afterwards, she stir-fried the individually-wrapped fillings in oil until they got crispy. Placing the Chinese dumplings on a plate, she took out a pair of chopsticks and began savoring the taste. When she had a hard time sleeping at night, eating her dumplings would always help. She didn’t really know why, but perhaps it is because they reminded her of her roots; through them, she remembered the old home she used to live in with her family back in China."

## keep this story
p8 = "As the young couple strolled hand in hand through the park, a gust of wind whipped through the trees, sending a chill down their spines. It was as if the very air around them was trying to warn them of something sinister lurking just out of sight. But they shrugged off the feeling, dismissing it as nothing more than their overactive imaginations. They were in love, after all, and nothing could dampen their spirits. As they continued on their way, the clouds overhead grew darker and more ominous. A few drops of rain began to fall, followed by a rumble of thunder that echoed through the park. Still, the couple remained undaunted. They laughed and danced in the rain, oblivious to the danger that lurked just around the corner. But then, out of nowhere, a bolt of lightning struck a nearby tree, sending splinters flying in every direction. The couple shrieked and stumbled backwards, their hearts racing with fear. As they looked up at the sky, they realized that they had been foolish to ignore the warning signs. The clouds had been a deep shade of gray, the wind had been howling, and the air had been charged with electricity. All of the lesser words of foreshadowing had been there, but they had ignored them, too caught up in their own happiness to pay attention. As they huddled together, waiting for the storm to pass, they knew that they had been lucky. They had narrowly escaped disaster, but they had learned an important lesson. From now on, they would pay closer attention to the world around them, for they knew that the smallest details could hold the greatest warnings."

## keep this story
p9 = "Lena was a young girl who lived in a small village at the edge of a dense forest. She loved to explore the woods and often spent her afternoons wandering among the trees. One day, while she was out on a walk, she noticed a strange feeling in the air. It was as if the forest was holding its breath, waiting for something to happen. As Lena walked deeper into the woods, she began to see signs of danger. Trees were toppled over, and the underbrush was trampled down. The forest animals were nowhere to be seen, and the silence was eerie. Lena could feel her heart racing as she realized that something terrible had happened. As she continued on her path, Lena saw a shadow moving in the distance. It was too dark to make out what it was, but she knew that it wasn't human. She tried to turn back, but it was too late. The shadow was upon her, and Lena found herself face to face with a fearsome creature she had never seen before. Lena fought for her life, but the creature was too strong. She managed to escape, but she knew that she would never be the same again. From that day on, Lena never ventured into the forest alone, and the villagers whispered of the dangers that lurked in the woods. Years later, when Lena was an old woman, the village was attacked by a pack of savage beasts. Lena knew that they were the same creatures that had attacked her all those years ago. She fought bravely alongside the other villagers, but in the end, they were all killed. As Lena lay dying, she realized that the foreshadowing she had felt all those years ago had been a warning of the terrible fate that awaited her village."


## keep this story (chatGPT worked)
p10 = "Sophie was an avid reader who loved to explore the world of books. One day, while browsing through the shelves of her local library, she stumbled upon a mysterious old tome. The cover was worn and tattered, and the pages were yellowed with age. As she opened the book, Sophie felt a strange sensation wash over her. It was as if she had been transported to another time and place. The story within the pages was unlike anything she had ever read before, filled with twists and turns that kept her on the edge of her seat. As she read on, Sophie couldn't help but feel a sense of wonder and excitement. The words seemed to jump off the page, painting vivid pictures in her mind. The characters were so real, she felt as if she knew them personally. Before she knew it, hours had passed, and the library was closing for the night. As she closed the book, Sophie felt a pang of sadness, as if she was saying goodbye to dear friends. Over the coming days, Sophie found herself unable to stop thinking about the story. She re-read it several times, each time uncovering new details and hidden meanings. In the end, Sophie realized that the story had become more than just words on a page. It was a world she could escape to whenever she needed to, a place of wonder and magic that would always be there for her. And she knew that no matter how many books she read in the future, this one would always hold a special place in her heart."

p11 = "Once upon a time, there was a wealthy merchant named Thomas who lived in a grand mansion on the outskirts of a bustling city. Thomas was known for his generosity and his love of games, and he often hosted lavish parties for his friends and neighbors. One day, Thomas decided to invite his guests to a special party with a hint of mystery and intrigue. He told them that he had hidden a valuable treasure somewhere within his mansion, and that whoever found it would win a prize of great worth. The guests eagerly set to work searching the mansion for clues, scouring every room and hallway for any sign of the hidden treasure. But as the hours ticked by and the search grew more frantic, it became clear that the treasure was nowhere to be found. Just when everyone had given up hope, Thomas revealed the twist in the game. The treasure had never actually existed - it was all part of a ruse to test the guests' mettle and see who was truly worthy of his friendship. The guests were initially shocked and disappointed, but they soon realized that the true treasure was the experience itself - the thrill of the hunt, the camaraderie of the search party, and the satisfaction of knowing that they had been chosen to participate in such a special event."

## Two outlierts from two different sentences  (GREAT)
p12 = "Once upon a time, there was a young girl named Alice who lived in a small village. One day, while walking through the forest, she stumbled upon a strange-looking key. Excited by her discovery, Alice searched high and low for the lock that the key would fit. Finally, after hours of searching, she found an old door hidden in the bushes. With trembling hands, she inserted the key and turned it slowly. To her surprise, the door creaked open to reveal a staircase leading down into the darkness. Brimming with curiosity, Alice descended the stairs and soon found herself in a vast underground chamber filled with glittering jewels and precious artifacts. Just as she was about to pick up a gleaming diamond, she heard footsteps approaching. Suddenly, a tall figure emerged from the shadows, brandishing a sword. It was the fierce dragon who had guarded the treasure for centuries! With a gasp, Alice realized that she was in mortal danger. But instead of fleeing, she stood her ground and looked the dragon straight in the eye. To her amazement, the dragon lowered its sword and spoke in a gentle voice. I have been waiting for someone like you for a long time, it said. Someone brave enough to face me and claim the treasure. You have passed the test, Alice. The treasure is yours."


p13 = "Shahjahan, the Mughal emperor, sat on his throne, lost in thought. His mind was consumed with grief and longing for his beloved wife, Mumtaz Mahal, who had passed away years ago. He yearned for a way to immortalize her memory, to create a monument that would stand the test of time and serve as a testament to their love. And so, he decided to build a grand mausoleum in her honor, unlike anything the world had ever seen. He commissioned the finest architects, craftsmen, and artisans to construct what would become known as the Taj Mahal. Years went by as the magnificent structure slowly took shape, rising from the ground like a shimmering ivory dream. Shahjahan poured all his love and passion into the project, often visiting the site to oversee the construction himself. Finally, the day arrived when the Taj Mahal was completed. Shahjahan stood before it, tears streaming down his face, as he gazed upon the breathtaking sight. As he turned to leave, he realized that his own legacy was now forever linked to the monument. And so, he whispered to himself, Let this monument be not just a tribute to my wife, but also a symbol of the grandeur of the Mughal Empire. And with that, Shahjahan walked away, leaving behind a legacy that would inspire generations to come."

p14 = "As a little girl, Emily loved visiting her grandparents' house. Her favorite room was the attic, where she would spend hours rummaging through old trunks filled with vintage clothes and mysterious objects. Years later, after her grandparents passed away, Emily inherited the house. She decided to renovate the attic and turn it into a cozy guest room. As she was cleaning out the trunks, she found a beautiful silver locket. She opened it and saw a picture of her grandfather and a woman she didn't recognize. The hint of a secret love affair between her grandfather and another woman crossed her mind. Emily decided to show the locket to her mother, who immediately recognized the woman in the picture. She told Emily that the woman was her grandmother's twin sister, who tragically died in a car accident before her grandparents got married. Emily was shocked but relieved that there was no scandalous secret. She decided to keep the locket as a precious family heirloom and a reminder of the mysterious stories hidden in her grandparents' house."

p15 = "As a little girl, Emily had always loved playing with her grandmother's antique dollhouse. It was a beautiful and intricate replica of their family's ancestral home, and Emily spent countless hours arranging the miniature furniture and dolls just so. One day, when Emily was all grown up, her grandmother passed away, leaving her the dollhouse in her will. Emily was overjoyed to finally have the dollhouse all to herself. But as she was dusting off the little figures inside, she noticed something strange. The dolls had moved from their previous positions, and one of them was missing entirely. Emily was confused, but shrugged it off as a trick of her imagination. However, as the days went by, she became more and more convinced that something strange was happening with the dollhouse. The dolls continued to move on their own, and Emily swore she could hear whispers and laughter coming from the miniature rooms. Finally, Emily had had enough. She took a closer look at the missing doll, and realized it was a tiny version of herself. Suddenly, it all clicked into place. The dollhouse was not a replica of their ancestral home, but a miniature version of Emily's own house, complete with all the family members, including herself. She had been playing with her own life all along, and now it was playing back."

p16 = "Alice was a successful businesswoman who had it all: a high-paying job, a beautiful home, and a loving husband. However, she couldn't shake the feeling that something was missing from her life. One day, Alice's husband surprised her with tickets to a tropical paradise. They spent the first few days lounging on the beach and exploring the local sights. On the fourth day, Alice's husband suggested they take a hike to a secluded waterfall. As they made their way through the jungle, Alice's husband suddenly stopped and turned to her. I have a confession to make, he said, his face pale. I've been having an affair. Alice's world came crashing down around her. She had suspected that something was off, but never in a million years did she think her husband would cheat on her. As she tried to process the news, she heard a rustling in the bushes behind them. Suddenly, a group of armed men burst out of the foliage and held them at gunpoint. It turned out that Alice's husband had been involved in some shady business dealings, and now they were both in grave danger."

p17 =  "There was a young couple named Jack and Emily who lived in a small town. They were deeply in love and planned to get married soon. One day, Jack received a job offer from a big city and decided to move there, leaving Emily behind. Emily was heartbroken but agreed to stay in the town until they got married.Months passed, and Jack never returned. Emily tried calling him, but he never answered. She decided to visit the city and look for him. She was shocked to find out that Jack had married someone else and had a new family. Emily was devastated and decided to return to the town. As she was walking through the woods, she heard a loud scream. She followed the sound and found a young girl lying on the ground, bleeding. The girl had been attacked by a wild animal, and Emily realized that she needed to act fast.She carried the girl to the nearest hospital and waited anxiously for the doctors to treat her. The girl's family arrived, and they were grateful to Emily for saving their daughter's life. They invited her to their home and offered her a job as a nurse for their daughter.Emily accepted the offer and started working for the family. As she was taking care of the girl, she realized that she had found a new purpose in life. She had always wanted to be a nurse, and this was her chance to fulfill her dream.Years passed, and Emily became an important member of the family. She had forgotten all about Jack and had moved on with her life. One day, a man came to the door, asking for Emily. It was Jack, and he had come to apologize for his behavior and to ask for her forgiveness.Emily was surprised but didn't know what to say. She had moved on with her life and didn't want to revisit the past. She politely declined his offer and continued with her work. She had found a new family and a new purpose in life, and nothing could change that.The twist in the story was that Emily found a new purpose in life after being heartbroken and betrayed by the one she loved. She moved on and found happiness in a different way, which made her a stronger and better person."

p18 = "As a child, Lily loved exploring the woods behind her house. She would often spend hours wandering through the trees, picking wildflowers, and watching the animals. But as she grew older, she became busy with school and other activities, and the woods became a distant memory.One day, as an adult, she decided to take a walk through the woods again. As she made her way down the familiar path, she noticed a dark cloud looming on the horizon. She didn't think much of it at first, but as she walked further into the woods, the sky grew darker, and the wind began to pick up.Suddenly, a branch snapped overhead, and Lily looked up to see a large tree falling towards her. She had no time to react and was hit by the falling tree, knocking her to the ground. She was lucky to survive the accident, but it left her with a deep fear of the woods and the dangers that lurked within.Looking back, Lily realized that the dark cloud on the horizon was a warning of the storm that was about to hit, and the snap of the branch was a foreshadowing of the danger that was to come. She vowed to never underestimate the power of nature again, and to always be prepared for the unexpected."

p19 = "Samantha was a successful detective, but she had a secret that she kept hidden from her colleagues. She was haunted by the unsolved case of her childhood friend, Lily, who had disappeared without a trace years ago.One day, while investigating a seemingly unrelated case, Samantha stumbled upon a clue that hinted at Lily's whereabouts. She couldn't believe her luck, but as she dug deeper, she began to realize that she was getting too close to the truth.The foreshadowing was clear in the form of threatening phone calls and anonymous messages warning her to back off. But Samantha was determined to find out what had happened to her friend.She followed the trail of clues to an abandoned warehouse on the outskirts of town, where she finally found Lily, alive but barely hanging on. The hint she had received earlier came in the form of a familiar scent that led her to the hidden room where Lily was being held captive.Samantha called for backup, and they were able to apprehend the kidnapper and bring Lily to safety. As she hugged her long-lost friend, Samantha knew that she had finally solved the case that had haunted her for so long."

p20 = "Once upon a time, there was a small village nestled in the mountains. The people of the village were content with their simple way of life and found joy in the little things. One day, a traveling storyteller came to the village and shared a tale of great adventure and heroism.The villagers listened with rapt attention, amazed at the incredible story they had just heard. But as the storyteller left, the villagers began to talk amongst themselves, each sharing their own interpretation of the tale.Some saw it as a thrilling adventure, while others found it to be a cautionary tale of the dangers of greed and ambition. Still, others found the story to be lacking in substance and depth, and criticized the storyteller for his simplistic narrative.The debate continued for days, with each person seeing the story through their own unique lens. In the end, the storyteller returned to the village, and the villagers asked him to share another tale. But this time, they listened with a newfound understanding that the quality of a story is truly a matter of perception.And so, they enjoyed the tale for what it was, without judgment or criticism, appreciating the beauty and richness of the story as they saw it."

p21 = "As she searched frantically for her engagement ring, she noticed a small crack in the window. Her heart sank as she realized the thief had returned."

p22 = "Sarah woke up to a beautiful sunrise on the day of her wedding. She couldn't believe how perfect everything was going. But as she walked down the aisle, a sudden gust of wind blew out all the candles in the church. She knew it was a sign, but it was too late to turn back."

p23 = "The young couple was on their honeymoon in Hawaii when they decided to go for a hike in the mountains. As they climbed higher and higher, they noticed that the sky was getting darker and darker. They should have turned back, but they didn't. By the time they reached the summit, a thunderstorm was raging all around them."

storyQualityEvaluator.initiateBertProcess(p23)
storyQualityEvaluator.computeMovingCosineSimilarity()
storyQualityEvaluator.plotCosineSimilaritiesBySentenceWord()